# Generated by Django 3.1 on 2021-01-20 22:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Tytuł')),
                ('date', models.DateField(verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('category', models.CharField(help_text='Tematyka portalu', max_length=60, verbose_name='Kategoria')),
                ('address', models.CharField(max_length=250, verbose_name='Adres redakcji')),
                ('email', models.EmailField(max_length=254)),
                ('logotype', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Logo')),
                ('comments', models.TextField(blank=True, verbose_name='Inne informacje')),
            ],
        ),
        migrations.CreateModel(
            name='TaskBeforeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(verbose_name='Dodatkowe informacje')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_patronage.event', verbose_name='Wydarzenie')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAfterEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_materials_after_event', models.BooleanField(default=False, verbose_name='Wysłane materiały pokonferencyjne')),
                ('date_when_send', models.DateField(null=True, verbose_name='Data')),
                ('comments', models.TextField(blank=True, verbose_name='Dodatkowe informacje')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_patronage.event', verbose_name='Wydarzenie')),
                ('portal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='media_patronage.portal', verbose_name='Portal')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=20, verbose_name='Nazwisko')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phone_field.models.PhoneField(max_length=31)),
                ('comments', models.TextField(blank=True, verbose_name='Komentarz')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_patronage.portal', verbose_name='Portal')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='portals_cooperating',
            field=models.ManyToManyField(to='media_patronage.Portal', verbose_name='Portale współpracujące'),
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_patronage.event')),
                ('to_who', models.ManyToManyField(related_name='person_address', to='media_patronage.Person')),
            ],
        ),
        migrations.CreateModel(
            name='CooperationTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_for_portal', models.TextField(verbose_name='Usługi swiadczone dla poortalu')),
                ('services_provided_by_portal', models.TextField(verbose_name='Usługi świadczone przez portal')),
                ('comments', models.TextField(blank=True, verbose_name='Uwagi')),
                ('date_update', models.DateField(default=datetime.datetime(2021, 1, 20, 22, 49, 3, 875495, tzinfo=utc), verbose_name='Data dodania warunków wspólpracy')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_patronage.event')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_patronage.portal')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Tytuł')),
                ('published_date', models.DateField(verbose_name='Data publikacji')),
                ('pdf_article', models.FileField(null=True, upload_to='articles/', verbose_name='PDF')),
                ('event', models.ForeignKey(help_text='Wydarzenie, którego dotyczy', on_delete=django.db.models.deletion.CASCADE, to='media_patronage.event', verbose_name='Wydarzenie')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_patronage.portal', verbose_name='Na jakim portalu opublikowane')),
            ],
        ),
    ]
