# Generated by Django 3.1 on 2020-08-22 14:13

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('logotype', models.ImageField(upload_to='logo/')),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskBeforeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_invitation_to_portals', models.BooleanField(default=False)),
                ('when_send_invitation', models.DateField()),
                ('comments', models.TextField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='media_patronage.event')),
                ('portals_invited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_patronage.portal')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAfterEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_materials_after_event', models.BooleanField(default=False)),
                ('comments', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_patronage.event')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_patronage.portal')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phone_field.models.PhoneField(max_length=31)),
                ('comments', models.TextField()),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_patronage.portal')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='portals_cooperating',
            field=models.ManyToManyField(to='media_patronage.Portal'),
        ),
        migrations.CreateModel(
            name='CooperationTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_for_portal', models.TextField()),
                ('services_provided_by_portal', models.TextField()),
                ('comments', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_patronage.event')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_patronage.portal')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('published_date', models.DateField()),
                ('pdf_article', models.FileField(null=True, upload_to='articles/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_patronage.event')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_patronage.portal')),
            ],
        ),
    ]
