# Generated by Django 3.1 on 2020-08-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_patronage', '0003_auto_20200823_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal',
            name='address',
            field=models.CharField(max_length=250, verbose_name='Adres redakcji'),
        ),
        migrations.AlterField(
            model_name='portal',
            name='category',
            field=models.CharField(help_text='Tematyka portalu', max_length=60, verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='portal',
            name='comments',
            field=models.TextField(verbose_name='Inne informacje'),
        ),
        migrations.AlterField(
            model_name='portal',
            name='logotype',
            field=models.ImageField(upload_to='logo/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='portal',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nazwa'),
        ),
    ]
