# Generated by Django 3.1 on 2021-01-20 23:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('media_patronage', '0004_auto_20210120_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperationterms',
            name='date_update',
            field=models.DateField(default=datetime.datetime(2021, 1, 20, 23, 33, 28, 332275, tzinfo=utc), verbose_name='Data dodania warunków wspólpracy'),
        ),
    ]
