# Generated by Django 3.1 on 2020-08-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_patronage', '0004_auto_20200823_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal',
            name='logotype',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Logo'),
        ),
    ]
