# Generated by Django 3.1 on 2020-08-23 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_patronage', '0005_auto_20200823_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Komentarz'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='person',
            name='portal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_patronage.portal', verbose_name='Portal'),
        ),
        migrations.AlterField(
            model_name='portal',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Inne informacje'),
        ),
    ]
