# Generated by Django 3.1 on 2021-01-24 13:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('media_patronage', '0005_auto_20210120_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperationterms',
            name='date_update',
            field=models.DateField(default=datetime.datetime(2021, 1, 24, 13, 46, 3, 418857, tzinfo=utc), verbose_name='Data dodania warunków wspólpracy'),
        ),
    ]
