# Generated by Django 3.1 on 2020-09-05 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_patronage', '0006_auto_20200823_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskafterevent',
            name='date_when_send',
            field=models.DateField(null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='event',
            name='portals_cooperating',
            field=models.ManyToManyField(to='media_patronage.Portal', verbose_name='Portale współpracujące'),
        ),
        migrations.AlterField(
            model_name='taskafterevent',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Dodatkowe informacje'),
        ),
        migrations.AlterField(
            model_name='taskafterevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_patronage.event', verbose_name='Wydarzenie'),
        ),
        migrations.AlterField(
            model_name='taskafterevent',
            name='portal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_patronage.portal', verbose_name='Portal'),
        ),
        migrations.AlterField(
            model_name='taskafterevent',
            name='send_materials_after_event',
            field=models.BooleanField(default=False, verbose_name='Wysłane materiały pokonferencyjne'),
        ),
        migrations.AlterField(
            model_name='taskbeforeevent',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Dodatkowe informacje'),
        ),
        migrations.AlterField(
            model_name='taskbeforeevent',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='media_patronage.event', verbose_name='Wydarzenie'),
        ),
        migrations.AlterField(
            model_name='taskbeforeevent',
            name='portals_invited',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_patronage.portal', verbose_name='Zaproszone do współpracy portale'),
        ),
        migrations.AlterField(
            model_name='taskbeforeevent',
            name='send_invitation_to_portals',
            field=models.BooleanField(default=False, verbose_name='czy wysłane zaproszenie do portali tematynych'),
        ),
        migrations.AlterField(
            model_name='taskbeforeevent',
            name='when_send_invitation',
            field=models.DateField(blank=True, null=True, verbose_name='Kiedy zostało wysłane zaproszenie'),
        ),
    ]
