# Generated by Django 3.1 on 2020-09-05 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_patronage', '0007_auto_20200905_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskafterevent',
            name='portal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='media_patronage.portal', verbose_name='Portal'),
        ),
    ]
