# Generated by Django 3.1 on 2021-02-17 20:18

import cloudinary.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('media_patronage', '0007_auto_20210124_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperationterms',
            name='date_update',
            field=models.DateField(default=datetime.datetime(2021, 2, 17, 20, 18, 56, 738825, tzinfo=utc), verbose_name='Data dodania warunków wspólpracy'),
        ),
        migrations.AlterField(
            model_name='portal',
            name='logotype',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='logotype'),
        ),
    ]
