# Generated by Django 3.1 on 2020-09-14 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_patronage', '0009_auto_20200911_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='to_who',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addressee', to='media_patronage.person'),
        ),
    ]
