# Generated by Django 3.1 on 2021-02-17 22:33

import cloudinary.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('media_patronage', '0009_auto_20210217_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pdf_article',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='pdf'),
        ),
        migrations.AlterField(
            model_name='cooperationterms',
            name='date_update',
            field=models.DateField(default=datetime.datetime(2021, 2, 17, 22, 33, 45, 226956, tzinfo=utc), verbose_name='Data dodania warunków wspólpracy'),
        ),
    ]
