# Generated by Django 3.1 on 2020-09-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_patronage', '0010_auto_20200914_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='to_who',
        ),
        migrations.AddField(
            model_name='email',
            name='to_who',
            field=models.ManyToManyField(null=True, related_name='person_address', to='media_patronage.Person'),
        ),
    ]
