# Generated by Django 3.1 on 2020-11-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_patronage', '0011_auto_20200925_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskbeforeevent',
            name='to_who',
            field=models.ManyToManyField(to='media_patronage.Person'),
        ),
        migrations.AlterField(
            model_name='email',
            name='to_who',
            field=models.ManyToManyField(related_name='person_address', to='media_patronage.Person'),
        ),
    ]
