# Generated by Django 3.1 on 2020-11-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_patronage', '0012_auto_20201108_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskbeforeevent',
            name='portals_invited',
        ),
        migrations.RemoveField(
            model_name='taskbeforeevent',
            name='send_invitation_to_portals',
        ),
        migrations.RemoveField(
            model_name='taskbeforeevent',
            name='to_who',
        ),
        migrations.RemoveField(
            model_name='taskbeforeevent',
            name='when_send_invitation',
        ),
        migrations.AddField(
            model_name='email',
            name='date',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
    ]
