# Generated by Django 3.1 on 2020-11-10 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_patronage', '0013_auto_20201109_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskbeforeevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_patronage.event', verbose_name='Wydarzenie'),
        ),
    ]
