# Generated by Django 3.1 on 2020-11-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_patronage', '0014_auto_20201110_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskbeforeevent',
            name='comments',
            field=models.TextField(verbose_name='Dodatkowe informacje'),
        ),
    ]
