# Generated by Django 3.1 on 2020-11-16 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_patronage', '0015_auto_20201110_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperationterms',
            name='date_update',
            field=models.DateField(default=datetime.datetime(2020, 11, 16, 22, 5, 51, 15386), verbose_name='Data dodania warunków wspólpracy'),
        ),
        migrations.AlterField(
            model_name='cooperationterms',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Uwagi'),
        ),
        migrations.AlterField(
            model_name='cooperationterms',
            name='services_for_portal',
            field=models.TextField(verbose_name='Usługi swiadczone dla poortalu'),
        ),
        migrations.AlterField(
            model_name='cooperationterms',
            name='services_provided_by_portal',
            field=models.TextField(verbose_name='Usługi świadczone przez portal'),
        ),
    ]
