# Generated by Django 3.1 on 2020-11-16 22:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('media_patronage', '0016_auto_20201116_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperationterms',
            name='date_update',
            field=models.DateField(default=datetime.datetime(2020, 11, 16, 22, 8, 3, 929850, tzinfo=utc), verbose_name='Data dodania warunków wspólpracy'),
        ),
    ]
